// Fill these after creating your Supabase project.
window.APP_CONFIG = {
  SUPABASE_URL: "YOUR_SUPABASE_PROJECT_URL",
  SUPABASE_PUBLISHABLE_KEY: "YOUR_SUPABASE_PUBLISHABLE_KEY",
  RAZORPAY_KEY_ID: "YOUR_RAZORPAY_KEY_ID"
};
